name: Generate Metrics

on:
  schedule:
    - cron: "0 3 * * *"   # every day at 03:00 UTC
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write          # required to commit the generated SVG

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}

          # Profile
          user: rehmansheikh222
          template: classic
          base: header, activity, community
          config_timezone: UTC

          # Output
          filename: metrics.svg
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 5

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Organizations
          plugin_organizations: yes
          organizations_affiliations: owner, collaborator, member

          # (optional but nice) Languages mini-card
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_languages_limit: 8
